version: '3'

networks:
  keycloak:
    external:
      name: keycloak-net

services:
  users_postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: keycloak_users
      POSTGRES_PASSWORD: p0stgr3s
    ports:
      - "5433:5432"
    volumes:
      - ~/postgres/data:/var/lib/postgresql/data
    networks:
      - keycloak
  keycloak_postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: p0stgr3s
    volumes:
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./keycloak-postgres-data:/var/lib/postgres/data
    ports:
      - "5432:5432"
    networks:
      - keycloak
  keycloak:
    build: .
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: teste123
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_postgres
      DB_USER: postgres
      DB_PASSWORD: p0stgr3s
      DB_DATABASE: keycloak
      DB_SCHEMA: public
    ports:
      - 8080:8080
    networks:
      - keycloak
    depends_on:
      - keycloak_postgres