logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        autoconfigure: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/demo
          jwk-set-uri: http://keycloak:8080/auth/realms/demo/protocol/openid-connect/certs